import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%DOLPHIN_AGENT_HOOK_PORT%"=="" if defined DOLPHIN_AGENT_HOOK_ENDPOINT if exist "%DOLPHIN_AGENT_HOOK_ENDPOINT%" call "%DOLPHIN_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%DOLPHIN_AGENT_HOOK_TOKEN%"=="" if not "%DOLPHIN_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\dolphin-dev\\agent-hooks" for /r "%APPDATA%\\dolphin-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%DOLPHIN_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\dolphin\\agent-hooks" for /r "%APPDATA%\\dolphin\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%DOLPHIN_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set DOLPHIN_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%DOLPHIN_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__dolphin_read_ancestor_var() {',
    '  __dolphin_name="$1"',
    '  __dolphin_pid="${PPID:-}"',
    '  while [ -n "$__dolphin_pid" ] && [ "$__dolphin_pid" != "0" ] && [ "$__dolphin_pid" != "1" ]; do',
    '    __dolphin_value=""',
    '    if [ -r "/proc/$__dolphin_pid/environ" ]; then',
    '      __dolphin_value=$(tr "\\000" "\\n" < "/proc/$__dolphin_pid/environ" 2>/dev/null | sed -n "s/^${__dolphin_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__dolphin_value" ]; then',
    '      __dolphin_value=$(ps eww -p "$__dolphin_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__dolphin_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__dolphin_value" ]; then',
    '      printf "%s\\n" "$__dolphin_value"',
    '      return 0',
    '    fi',
    '    __dolphin_pid=$(ps -o ppid= -p "$__dolphin_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__dolphin_fill_from_ancestor() {',
    '  __dolphin_name="$1"',
    '  case "$__dolphin_name" in',
    '    DOLPHIN_AGENT_HOOK_ENDPOINT) [ -z "${DOLPHIN_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    DOLPHIN_AGENT_HOOK_PORT) [ -z "${DOLPHIN_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    DOLPHIN_AGENT_HOOK_TOKEN) [ -z "${DOLPHIN_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    DOLPHIN_AGENT_HOOK_ENV) [ -z "${DOLPHIN_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    DOLPHIN_AGENT_HOOK_VERSION) [ -z "${DOLPHIN_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    DOLPHIN_PANE_KEY) [ -z "${DOLPHIN_PANE_KEY:-}" ] || return 0 ;;',
    '    DOLPHIN_TAB_ID) [ -z "${DOLPHIN_TAB_ID:-}" ] || return 0 ;;',
    '    DOLPHIN_WORKTREE_ID) [ -z "${DOLPHIN_WORKTREE_ID:-}" ] || return 0 ;;',
    '    DOLPHIN_AGENT_LAUNCH_TOKEN) [ -z "${DOLPHIN_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __dolphin_value=$(__dolphin_read_ancestor_var "$__dolphin_name") || return 0',
    '  [ -n "$__dolphin_value" ] && export "$__dolphin_name=$__dolphin_value"',
    '}',
    '__dolphin_endpoint_value() {',
    '  __dolphin_endpoint_name="$1"',
    '  __dolphin_endpoint_path="$2"',
    '  sed -n "s/^${__dolphin_endpoint_name}=//p" "$__dolphin_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__dolphin_fill_from_endpoint_file() {',
    '  __dolphin_endpoint_path="$1"',
    '  [ -r "$__dolphin_endpoint_path" ] || return 0',
    '  __dolphin_endpoint_port=$(__dolphin_endpoint_value DOLPHIN_AGENT_HOOK_PORT "$__dolphin_endpoint_path")',
    '  if [ -n "${DOLPHIN_AGENT_HOOK_PORT:-}" ] && [ -n "$__dolphin_endpoint_port" ] && [ "$__dolphin_endpoint_port" != "$DOLPHIN_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __dolphin_endpoint_name in DOLPHIN_AGENT_HOOK_PORT DOLPHIN_AGENT_HOOK_TOKEN DOLPHIN_AGENT_HOOK_ENV DOLPHIN_AGENT_HOOK_VERSION; do',
    '    eval "__dolphin_current=\\${$__dolphin_endpoint_name:-}"',
    '    [ -z "$__dolphin_current" ] || continue',
    '    __dolphin_endpoint_value=$(__dolphin_endpoint_value "$__dolphin_endpoint_name" "$__dolphin_endpoint_path")',
    '    [ -n "$__dolphin_endpoint_value" ] && export "$__dolphin_endpoint_name=$__dolphin_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Dolphin pane/hook metadata, so recover it before posting.',
    'for __dolphin_name in DOLPHIN_AGENT_HOOK_ENDPOINT DOLPHIN_AGENT_HOOK_PORT DOLPHIN_AGENT_HOOK_TOKEN DOLPHIN_AGENT_HOOK_ENV DOLPHIN_AGENT_HOOK_VERSION DOLPHIN_PANE_KEY DOLPHIN_TAB_ID DOLPHIN_WORKTREE_ID DOLPHIN_AGENT_LAUNCH_TOKEN; do',
    '  __dolphin_fill_from_ancestor "$__dolphin_name"',
    'done',
    'if [ -n "$DOLPHIN_AGENT_HOOK_ENDPOINT" ] && [ -r "$DOLPHIN_AGENT_HOOK_ENDPOINT" ]; then',
    '  __dolphin_fill_from_endpoint_file "$DOLPHIN_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# DOLPHIN_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$DOLPHIN_AGENT_HOOK_TOKEN" ] && [ -n "$DOLPHIN_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/dolphin-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/dolphin-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dolphin-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dolphin-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/dolphin/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dolphin/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^DOLPHIN_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$DOLPHIN_AGENT_HOOK_PORT" ]; then',
    '      __dolphin_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$DOLPHIN_AGENT_HOOK_PORT" ] || [ -z "$DOLPHIN_AGENT_HOOK_TOKEN" ] || [ -z "$DOLPHIN_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${DOLPHIN_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Dolphin-Agent-Hook-Token: ${DOLPHIN_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${DOLPHIN_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${DOLPHIN_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${DOLPHIN_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${DOLPHIN_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${DOLPHIN_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${DOLPHIN_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
